### ISSUE TITLE
Opera does not sync when joined to fakenet which already contains transactions

### ISSUE THREAD

**Issue by thaarok** [Fantom-foundation/Sonic#5]
Opera correctly joins fakenet, if it does not contain any txs yet, but after sending first tx, additional Opera nodes are unable to join - stay stuck at block 1.

When connected using `opera attach`, `admin.peers` confirms the node see the other nodes.

Following Norma scenario reproduce the bug:
```yml
# This scenario reproduce bug, where go-opera-norma does not sync
# when joined into a network, where are already present some txs.

name: Reproduce go-opera-norma bug
duration: 60
num_validators: 3

nodes:
  - name: B # node starting after the app start - never sync
    instances: 1
    start: 1

applications:
  - name: counter
    start: 0
    end: 60
    accounts: 2
    rate:
      constant: 2 # txs/s
```

```
2023/06/08 08:02:54 Nodes: 4, block heights: [89 *1* 89 89], tx/s: [1.8315018 1.8450185 1.8181819], txs: 1, gas: 28693, block processing: [2.599ms 2.724ms 2.432ms]
```
Opera version: 9d4226c565bd69930f2e95f33d36690e21004db8
Norma version: [`f9f5a9d`](https://github.com/Fantom-foundation/Norma/commit/f9f5a9d9063bbd5cf73c2791fe517fd8d07fbc03) (main)
